[project]
name = "kg-evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kg-gen>=0.1.7",
    "networkx>=3.4.2",
    "sentence-transformers>=4.1.0",
]
